using UnityEngine;

namespace PoSumo
{
    /// Spoken voice lines for one fighter: happy, sad and insults, each a set of
    /// five clips where 1 is the mildest read and 5 the strongest.
    ///
    /// Clips live in Resources/ and are found by naming convention, so adding
    /// Nick_Happy_1..5 / Nick_Sad1..5 / Nick_Insult_1..5 gives Nick a voice with
    /// no code change. A fighter with no clips is silent rather than an error —
    /// only Matt is recorded today.
    ///
    /// What drives each set:
    ///   sad     being hit (level from impact force), losing a round (4),
    ///           losing the match (5)
    ///   happy   live dominance climbing past thresholds, winning a round (4),
    ///           winning the match (5)
    ///   insult  roughly every insultInterval seconds while a round is live
    ///
    /// Dominance comes from Systems_FightHud, the same signal Systems_FaceMood
    /// already uses to pick the expression — so what Matt says and what his face
    /// does can never disagree.
    ///
    /// Spawned at runtime by Systems_GameMatchManager, one per fighter.
    public sealed class Systems_FighterVoice : MonoBehaviour
    {
        public string fighterBehaviorName = "Matt";

        [Tooltip("Pitch multiplier. The second of two identical fighters is dropped so a Matt-vs-Matt bout does not sound like one man arguing with himself.")]
        public float pitchScale = 1f;
        [Range(0f, 1f)] public float volume = 0.9f;

        [Header("Sad (being hit)")]
        [Tooltip("Impact speed (m/s) that produces the mildest sad line.")]
        public float hitMinSpeed = 2.6f;
        [Tooltip("Impact speed (m/s) that produces the strongest sad line.")]
        public float hitMaxSpeed = 8.5f;

        [Header("Happy (doing well)")]
        [Tooltip("Dominance (0-100) above which he starts gloating.")]
        public float happyDominance = 62f;
        [Tooltip("Dominance at which the strongest in-round happy line fires.")]
        public float happyDominanceMax = 92f;
        [Tooltip("Dominance must fall back below this before another happy line can fire, so a steady lead does not loop.")]
        public float happyRearmDominance = 55f;

        [Header("Insults")]
        public float insultInterval = 8f;
        [Tooltip("Random +/- spread on the interval so the cadence is not metronomic.")]
        public float insultJitter = 1.6f;

        [Header("Pacing")]
        [Tooltip("Minimum gap between ANY two lines from this fighter.")]
        public float minGapSeconds = 1.4f;

        private const int LEVELS = 5;

        private Systems_VoiceGains _gains;
        private AudioClip[] _happy;
        private AudioClip[] _sad;
        private AudioClip[] _insult;

        private AudioSource _source;
        private Systems_GameMatchManager _manager;
        private Systems_FightHud _hud;
        private Agent_Biped _fighter;
        private Agent_BipedBody _body;
        private bool _fighterIsA;

        private float _nextAllowedTime;
        private float _nextInsultTime;
        private bool _happyArmed = true;
        private bool _matchDecided;

        private void Start()
        {
            _manager = FindAnyObjectByType<Systems_GameMatchManager>();
            _hud = FindAnyObjectByType<Systems_FightHud>();
            if (_manager == null)
            {
                enabled = false;
                return;
            }

            // Resolve which side this voice belongs to. Matched by behaviour name
            // the same way Systems_FaceMood does it.
            if (_manager.wrestlerA != null && _manager.wrestlerA.behaviorName == fighterBehaviorName)
            {
                _fighter = _manager.wrestlerA;
                _fighterIsA = true;
            }
            else if (_manager.wrestlerB != null && _manager.wrestlerB.behaviorName == fighterBehaviorName)
            {
                _fighter = _manager.wrestlerB;
                _fighterIsA = false;
            }
            if (_fighter == null)
            {
                enabled = false;
                return;
            }
            _body = _fighter.GetComponent<Agent_BipedBody>();

            // Regenerated by PoSumo > Normalize Voice Levels. Absent asset is not
            // an error — every clip then plays at its recorded level, as before.
            _gains = Resources.Load<Systems_VoiceGains>("VoiceGains");

            _happy = LoadSet("Happy");
            _sad = LoadSet("Sad");
            _insult = LoadSet("Insult");
            if (_happy == null && _sad == null && _insult == null)
            {
                // No recorded voice for this fighter. Silent, not broken.
                enabled = false;
                return;
            }

            _source = gameObject.AddComponent<AudioSource>();
            _source.playOnAwake = false;
            _source.loop = false;
            // 2D with manual pan, matching Systems_MatchAudio: true 3D falloff
            // pumps with the follow camera's zoom in an orthographic game.
            _source.spatialBlend = 0f;

            _manager.RoundEnded += OnRoundEnded;
            _manager.MatchEnded += OnMatchEnded;
            _manager.MatchReset += OnMatchReset;
            _manager.RoundStarted += OnRoundStarted;

            ScheduleInsult();
        }

        private void OnEnable()
        {
            Sensor_Impact.AnyImpact += OnImpact;
        }

        private void OnDisable()
        {
            // Static event — a missed unsubscribe keeps a dead scene's voice alive
            // across a scene load.
            Sensor_Impact.AnyImpact -= OnImpact;
            if (_manager != null)
            {
                _manager.RoundEnded -= OnRoundEnded;
                _manager.MatchEnded -= OnMatchEnded;
                _manager.MatchReset -= OnMatchReset;
                _manager.RoundStarted -= OnRoundStarted;
            }
        }

        /// Loads `<Fighter>_<Kind>_1..5` from Resources. That is the one naming
        /// convention for voice clips — `Matt_Happy_1.wav`, `Nick_Sad_3.wav`.
        ///
        /// This used to try a second, un-underscored spelling as well, because
        /// Matt's Sad recordings shipped as `Matt_Sad1` while everything else in
        /// his own set used `Matt_Happy_1`. Those files have been renamed, so the
        /// fallback is gone: a clip that does not load now means the file is
        /// misnamed, and silently accepting a second spelling only guaranteed the
        /// next set would be inconsistent too.
        private AudioClip[] LoadSet(string kind)
        {
            var clips = new AudioClip[LEVELS];
            int found = 0;
            for (int level = 0; level < LEVELS; level++)
            {
                int n = level + 1;
                AudioClip clip = Resources.Load<AudioClip>($"{fighterBehaviorName}_{kind}_{n}");
                clips[level] = clip;
                if (clip != null)
                {
                    found++;
                }
            }
            if (found == 0)
            {
                return null;
            }
            if (found < LEVELS)
            {
                Debug.LogWarning($"Systems_FighterVoice ({fighterBehaviorName}): only {found}/{LEVELS} " +
                                 $"{kind} clips found in Resources; missing levels fall back to the nearest one.");
            }
            return clips;
        }

        // ------------------------------------------------------------- events

        private void OnRoundStarted()
        {
            _happyArmed = true;
            ScheduleInsult();
        }

        private void OnRoundEnded(Agent_Biped winner, Agent_Biped loser)
        {
            if (_matchDecided)
            {
                return;   // the match-end line owns that moment
            }
            if (winner == _fighter)
            {
                Say(_happy, 4);
            }
            else if (loser == _fighter)
            {
                Say(_sad, 4);
            }
            // A draw gets nothing.
        }

        private void OnMatchEnded(Agent_Biped winner)
        {
            _matchDecided = true;
            // Strongest read in the set is reserved for taking or losing the match.
            Say(winner == _fighter ? _happy : _sad, 5, force: true);
        }

        private void OnMatchReset()
        {
            _matchDecided = false;
            _happyArmed = true;
            ScheduleInsult();
        }

        private void OnImpact(Sensor_Impact sensor, Collision2D collision)
        {
            // Only hits this fighter RECEIVES from the opponent. Ground contact and
            // hits he delivers are somebody else's business.
            if (_body == null || sensor == null || sensor.owner != _body)
            {
                return;
            }
            var other = collision.collider.GetComponentInParent<Agent_BipedBody>();
            if (other == null || other == _body)
            {
                return;
            }

            float speed = collision.relativeVelocity.magnitude;
            if (speed < hitMinSpeed)
            {
                return;
            }
            Say(_sad, LevelFrom(speed, hitMinSpeed, hitMaxSpeed));
        }

        // -------------------------------------------------------------- tick

        private void Update()
        {
            if (_manager == null || _matchDecided)
            {
                return;
            }

            bool roundLive = _manager.RoundActive;

            // Insults only while the round is live, so they never talk over the
            // countdown, the taiko, the gong or the result card.
            if (roundLive && _insult != null && Time.time >= _nextInsultTime)
            {
                ScheduleInsult();
                Say(_insult, Random.Range(1, LEVELS + 1));
            }

            if (!roundLive || _hud == null || _happy == null)
            {
                return;
            }

            float dominance = _fighterIsA ? _hud.DominanceA : _hud.DominanceB;

            // One line per surge: he has to drop back to the rearm threshold before
            // gloating again, otherwise a steady lead loops the happy set forever.
            if (_happyArmed && dominance >= happyDominance)
            {
                _happyArmed = false;
                Say(_happy, LevelFrom(dominance, happyDominance, happyDominanceMax));
            }
            else if (!_happyArmed && dominance < happyRearmDominance)
            {
                _happyArmed = true;
            }
        }

        private void ScheduleInsult()
        {
            _nextInsultTime = Time.time + insultInterval + Random.Range(-insultJitter, insultJitter);
        }

        // ------------------------------------------------------------ playing

        /// Map a measured value onto 1..5.
        private static int LevelFrom(float value, float min, float max)
        {
            float t = Mathf.Clamp01((value - min) / Mathf.Max(0.01f, max - min));
            return Mathf.Clamp(Mathf.FloorToInt(t * LEVELS) + 1, 1, LEVELS);
        }

        /// Nearest available clip at or below `level`, then above. Lets a partial
        /// set (say only 1, 3 and 5 recorded) still cover the whole range.
        private AudioClip Pick(AudioClip[] set, int level)
        {
            if (set == null)
            {
                return null;
            }
            int index = Mathf.Clamp(level - 1, 0, LEVELS - 1);
            for (int offset = 0; offset < LEVELS; offset++)
            {
                int below = index - offset;
                if (below >= 0 && set[below] != null)
                {
                    return set[below];
                }
                int above = index + offset;
                if (above < LEVELS && set[above] != null)
                {
                    return set[above];
                }
            }
            return null;
        }

        private void Say(AudioClip[] set, int level, bool force = false)
        {
            if (_source == null)
            {
                return;
            }
            // One voice per fighter: a new line cuts the old one rather than
            // overlapping it, which is how a person actually talks. `force` is for
            // the match-decided line, which always wins.
            if (!force && (Time.time < _nextAllowedTime || _source.isPlaying))
            {
                return;
            }
            AudioClip clip = Pick(set, level);
            if (clip == null)
            {
                return;
            }
            _nextAllowedTime = Time.time + Mathf.Max(minGapSeconds, clip.length * 0.6f);
            _source.pitch = pitchScale;
            _source.panStereo = Pan();
            _source.clip = clip;
            // Per-clip correction from the normalization pass. The raw recordings
            // sit 20.7 dB apart in RMS and Nick's whole set is ~7 dB under Matt's,
            // so a flat volume made one fighter mumble and the other shout.
            // Missing entries return 1, so an unmeasured clip is uncorrected
            // rather than silent.
            _source.volume = volume * (_gains != null ? _gains.GainFor(clip.name) : 1f);
            _source.Play();
        }

        /// Pan by position in the ring, relative to the arena centre rather than
        /// the camera, so a fighter on the left stays on the left as the follow
        /// camera tracks across.
        private float Pan()
        {
            if (_fighter == null || _manager == null)
            {
                return 0f;
            }
            float centerX = _manager.transform.position.x;
            float half = Mathf.Max(0.01f, _manager.ringHalfWidth);
            return Mathf.Clamp((_fighter.TorsoX - centerX) / half, -1f, 1f) * 0.6f;
        }
    }
}
