<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" />
    <PackageReference Include="NAudio" />
    <PackageReference Include="NLayer.NAudioSupport" />
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>


</Project>
